### ISSUE TITLE
Async Requests Tab

### ISSUE THREAD

**Issue by pishty1** [spring-projects/spring-mvc-showcase#15]
Hello,

I am getting the following error when try to access the async requests tab:

java.lang.UnsupportedOperationException: No async support in a pre-Servlet 3.0 runtime

i was just wondering if anyone else encountered such a problem.

Many thanks for your time.

Pishty

**Comment by Tradunsky** [comment]
http://stackoverflow.com/questions/15159388/unit-testing-a-spring-mvc-controller-that-returns-deferredresult
