### ISSUE TITLE
Joda Time library should be updated from 1.6.2 to current version (2.3)

### ISSUE THREAD

**Issue by kamilsimek** [spring-projects/spring-mvc-showcase#22]
Hello spring-projects,

let me first thank you for the great set of examples provided by this project. For someone (like me) who is relatively new to Spring MVC this is of great help.

I would like to report the following:
with the currently shipped version of the Joda Time library (1.6.2) the spring-mvc-showcase throws an error when trying to use the "Redirecting" examples (org.springframework.samples.mvc.redirect, that rely on org.joda.time.LocalDate;).

Error:
cannot resolve org.joda.time.format.DateTimeFormatter.parseLocalDate

This is due to the Joda Time library (1.6.2) does not contain the parseLocalDate method, which is available only from version 2.0 of the Joda Time libraries.
See details that confirm this: 
http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormatter.html#parseLocalDate(java.lang.String)

If the dependecy in pom.xml could be updated that would be great.

Tested with Eclipse Kepler, Tomcat 7.047, Java 1.7.0 (build 1.7.0-b147)
## 

Kamil

**Comment by rstoyanchev** [comment]
Resolved via a30e404e00c17f8405bd3d81a6154c4432434456.
