### ISSUE TITLE
Can't build application

### ISSUE THREAD

**Issue by christianhenle** [spring-projects/spring-mvc-showcase#23]
Hello,

i tried to build the application on command-line.
But it doesn't work, her is my log.

noname:spring-mvc-showcase christianhenle$ mvn tomcat7:run
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-mvc-showcase 1.0.0-BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> tomcat7-maven-plugin:2.0:run (default-cli) @ spring-mvc-showcase >>>
[INFO] 
[INFO] --- aspectj-maven-plugin:1.2:compile (default) @ spring-mvc-showcase ---
[ERROR] The import javax.servlet.http.HttpServletRequest cannot be resolved
[ERROR] HttpServletRequest cannot be resolved to a type
[ERROR] The type javax.servlet.http.HttpServletRequest cannot be resolved. It is indirectly referenced from required .class files
[ERROR] The import javax.servlet.http.HttpServletRequest cannot be resolved
[ERROR] HttpServletRequest cannot be resolved to a type
[ERROR] The type org.joda.time.base.BaseLocal cannot be resolved. It is indirectly referenced from required .class files
[ERROR] The import org.hibernate.validator.constraints.NotEmpty cannot be resolved
[ERROR] NotEmpty cannot be resolved to a type
[ERROR] The type javax.servlet.http.HttpServletResponse cannot be resolved. It is indirectly referenced from required .class files
[ERROR] The import javax.servlet.http.HttpServletRequest cannot be resolved
[ERROR] The import javax.servlet.http.HttpServletResponse cannot be resolved
[ERROR] The import javax.servlet.http.HttpSession cannot be resolved
[ERROR] HttpServletRequest cannot be resolved to a type
[ERROR] HttpServletResponse cannot be resolved to a type
[ERROR] HttpSession cannot be resolved to a type
[ERROR] The import javax.servlet.http.HttpServletRequest cannot be resolved
[ERROR] HttpServletRequest cannot be resolved to a type
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.003s
[INFO] Finished at: Thu Dec 19 22:25:08 CET 2013
[INFO] Final Memory: 11M/147M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.2:compile (default) on project spring-mvc-showcase: Compiler errors :
[ERROR] error at import javax.servlet.http.HttpServletRequest;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/mapping/ClasslevelMappingController.java:3:0::0 The import javax.servlet.http.HttpServletRequest cannot be resolved
[ERROR] error at public @ResponseBody String byPathPattern(HttpServletRequest request) {
[ERROR] ^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/mapping/ClasslevelMappingController.java:21:0::0 HttpServletRequest cannot be resolved to a type
[ERROR] error at result.setResult(new ModelAndView("views/html", "javaBean", new JavaBean("bar", "apple")));
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/async/DeferredResultController.java:66:0::0 The type javax.servlet.http.HttpServletRequest cannot be resolved. It is indirectly referenced from required .class files
[ERROR] error at import javax.servlet.http.HttpServletRequest;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/mapping/MappingController.java:3:0::0 The import javax.servlet.http.HttpServletRequest cannot be resolved
[ERROR] error at public @ResponseBody String byPathPattern(HttpServletRequest request) {
[ERROR] ^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/mapping/MappingController.java:21:0::0 HttpServletRequest cannot be resolved to a type
[ERROR] error at (no source information available)
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/redirect/RedirectController.java:1:0::0 The type org.joda.time.base.BaseLocal cannot be resolved. It is indirectly referenced from required .class files
[ERROR] error at import org.hibernate.validator.constraints.NotEmpty;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/form/FormBean.java:10:0::0 The import org.hibernate.validator.constraints.NotEmpty cannot be resolved
[ERROR] error at @NotEmpty
[ERROR] ^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/form/FormBean.java:19:0::0 NotEmpty cannot be resolved to a type
[ERROR] error at (no source information available)
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/data/standard/StandardArgumentsController.java:1:0::0 The type javax.servlet.http.HttpServletResponse cannot be resolved. It is indirectly referenced from required .class files
[ERROR] error at import javax.servlet.http.HttpServletRequest;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/data/standard/StandardArgumentsController.java:11:0::0 The import javax.servlet.http.HttpServletRequest cannot be resolved
[ERROR] error at import javax.servlet.http.HttpServletResponse;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/data/standard/StandardArgumentsController.java:12:0::0 The import javax.servlet.http.HttpServletResponse cannot be resolved
[ERROR] error at import javax.servlet.http.HttpSession;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/data/standard/StandardArgumentsController.java:13:0::0 The import javax.servlet.http.HttpSession cannot be resolved
[ERROR] error at public @ResponseBody String standardRequestArgs(HttpServletRequest request, Principal user, Locale locale) {
[ERROR] ^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/data/standard/StandardArgumentsController.java:27:0::0 HttpServletRequest cannot be resolved to a type
[ERROR] error at public @ResponseBody String response(HttpServletResponse response) {
[ERROR] ^^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/data/standard/StandardArgumentsController.java:48:0::0 HttpServletResponse cannot be resolved to a type
[ERROR] error at public @ResponseBody String session(HttpSession session) {
[ERROR] ^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/data/standard/StandardArgumentsController.java:65:0::0 HttpSession cannot be resolved to a type
[ERROR] error at import javax.servlet.http.HttpServletRequest;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/data/custom/CustomArgumentController.java:3:0::0 The import javax.servlet.http.HttpServletRequest cannot be resolved
[ERROR] error at void beforeInvokingHandlerMethod(HttpServletRequest request) {
[ERROR] ^^^^^^^^^^^^^^^^
[ERROR] /Users/christianhenle/git/spring-mvc-showcase/src/main/java/org/springframework/samples/mvc/data/custom/CustomArgumentController.java:15:0::0 HttpServletRequest cannot be resolved to a type
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by blackOcean** [comment]
Application is not able to find the server, for this error javax.servlet.http.HttpServletRequest; Please right click on the project and go to target runtime and select any server like tomcat 7 or tomcat 8 or jboss or any server.

**Comment by rafaferreira** [comment]
Did not work for me on Jetty or tomcat7 run too

**Comment by rstoyanchev** [comment]
Just upgraded and tested after a30e404e00c17f8405bd3d81a6154c4432434456.
