### ISSUE TITLE
Forms and File uploading is not working

### ISSUE THREAD

**Issue by blackOcean** [spring-projects/spring-mvc-showcase#39]
![image](https://cloud.githubusercontent.com/assets/10592462/8612298/d16166c2-26eb-11e5-8a89-28a8ec068752.png)

It shows No Such method error when I click on Form and File uploading tab. 
By the way great work.

**Comment by indyaah** [comment]
Looks like servlet api version issue. I'd start from checking dependency version and then container (ie tomcat/jettty etc) supported version.

Thanks,
Anuj

Sent via mobile, please excuse the brevity.




On Thu, Jul 9, 2015 at 9:41 PM -0700, "Sagar Rout" <notifications@github.com> wrote:
















It shows No Such method error when I click on Form and File uploading tab. 

By the way great work.

**Comment by rstoyanchev** [comment]
This should work now via a30e404e00c17f8405bd3d81a6154c4432434456.
