### ISSUE TITLE
Not able to unit test validations using MockMVC

### ISSUE THREAD

**Issue by jforjava1981** [spring-projects/spring-mvc-showcase#41]
Hi,

 I am starting out on using MockMVC and I dont understand why my validations (javax and hibernate) do not execute when I run my unit test. Here is the summary : 
1) I have a mvc controller annotated with @RestController. This controller has a method to delete resource. 
      uri to delete resource is : /myresources/{resourceId} (I have given context relative url)
      this method accepts the Path Parameter in resourceId parameter annotated with @PathParam,
      Also this parameter is annotated with two other annotations for validating the path parameter.
       i) @Pattern which is a javax.validation annotation which specifies following pattern : regexp=[0-9]{1,12} to accept only 1 to 12 digits as input
      ii) it has @NotBlank validation which is org.hibernate validation to check if its not empty

```
I am building standalone MockMVC setup and using perform method to call the url with path parameter value set to abcd : /myresources/abcd instead of valid intege.  At this point no validation is carried out and it throws NumberFormatException in my method. 
```

 So 
Should it not preempt the call by carrying out validation so that it doesn't reach my method?
If yes why its not working. If no is this possible in any way because I want to write unit test for each of the validations.

I found similar link on stackoverflow and giving that here for reference : 

http://stackoverflow.com/questions/27106298/mock-mvc-javax-validation-test

Please help.

**Comment by rstoyanchev** [comment]
I believe this was due to a missing el-api dependency. The tests pass now and they do test validation in the FormController. If you still have the issue, turn logging up for org.springframework and re-open issue.
