### ISSUE TITLE
Timezone configuration makes tests fail

### ISSUE THREAD

**Issue by 1kastner** [spring-projects/spring-mvc-showcase#50]
When I want to build the project with maven, it returns the following:

`Failed tests:   formattedCollection(org.springframework.samples.mvc.convert.ConvertControllerTests): Response content expected:<Converted formatted collection [Sun Jul 04 00:00:00 MESZ 2010, Mon Jul 04 00:00:00 MESZ 2011]> but was:<Converted formatted collection [Sun Jul 04 00:00:00 CEST 2010, Mon Jul 04 00:00:00 CEST 2011]>
  beanFormattedCollection(org.springframework.samples.mvc.convert.ConvertControllerTests): Response content expected:<Converted JavaBean formattedList=[Sun Jul 04 00:00:00 MESZ 2010, Mon Jul 04 00:00:00 MESZ 2011]> but was:<Converted JavaBean formattedList=[Sun Jul 04 00:00:00 CEST 2010, Mon Jul 04 00:00:00 CEST 2011]>
  date(org.springframework.samples.mvc.convert.ConvertControllerTests): Response content expected:<Converted date Sun Jul 04 00:00:00 MESZ 2010> but was:<Converted date Sun Jul 04 00:00:00 CEST 2010>
  beanDate(org.springframework.samples.mvc.convert.ConvertControllerTests): Response content expected:<Converted JavaBean date=Sun Jul 04 00:00:00 MESZ 2010> but was:<Converted JavaBean date=Sun Jul 04 00:00:00 CEST 2010>
  submitSuccess(org.springframework.samples.mvc.form.FormControllerTests): Flash attribute expected:<Form submitted successfully.  Bound properties name='Joe', age=56, birthDate=Tue Dec 16 00:00:00 MESZ 1941, phone='(347) 888-1234', currency=123.33, percent=0.89, inquiry=comment, inquiryDetails='what is?', subscribeNewsletter=false, additionalInfo={java=true, mvc=true}> but was:<Form submitted successfully.  Bound properties name='Joe', age=56, birthDate=Tue Dec 16 00:00:00 CEST 1941, phone='(347) 888-1234', currency=123.33, percent=0.89, inquiry=comment, inquiryDetails='what is?', subscribeNewsletter=false, additionalInfo={java=true, mvc=true}>
  submitSuccessAjax(org.springframework.samples.mvc.form.FormControllerTests): Model attribute 'message' expected:<Form submitted successfully.  Bound properties name='Joe', age=56, birthDate=Tue Dec 16 00:00:00 MESZ 1941, phone='(347) 888-1234', currency=123.33, percent=0.89, inquiry=comment, inquiryDetails='what is?', subscribeNewsletter=false, additionalInfo={java=true, mvc=true}> but was:<Form submitted successfully.  Bound properties name='Joe', age=56, birthDate=Tue Dec 16 00:00:00 CEST 1941, phone='(347) 888-1234', currency=123.33, percent=0.89, inquiry=comment, inquiryDetails='what is?', subscribeNewsletter=false, additionalInfo={java=true, mvc=true}>`

How can I fix this?

**Comment by 1kastner** [comment]
PS: The time zones are CEST and MESZ respectively. As they are both exactly midnight, they should differ.

**Comment by rstoyanchev** [comment]
The tests pass after the upgrade.
