### ISSUE TITLE
Error on pom.xml

### ISSUE THREAD

**Issue by roizpi** [spring-projects/spring-mvc-showcase#52]
Using Eclipe plugin Maven Integration for Eclipse 1.5.0:

On line 271:
`<executions>`
`<execution>`
`<goals>`
`<goal>compile</goal>`
`<goal>test-compile</goal>`
`</goals>`
`</execution>`
`</executions>`

Error:
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:aspectj-maven-plugin:1.2:compile (execution: default, phase: process-sources)

I have solved it adding an `<id>` and `<phase>` tags to the `<execution>` block.

**Comment by dzzxjl** [comment]
I meet the same problem

**Comment by crazyfzw** [comment]
So am  i, I soved it by useing eclipse quick fixes Mark goal test-compile as ignored in eclipse build eclipse,
after the  code change：

`				<executions>
					<execution>
						<id>install</id>
						<phase>install</phase>
						<goals>
							<goal>sources</goal>
						</goals>
					</execution>
				</executions>`

**Comment by crazyfzw** [comment]
So am i, I soved it by useing eclipse quick fixes Mark goal test-compile as ignored in eclipse build eclipse

**Comment by sschober** [comment]
See this answer: http://stackoverflow.com/a/43508339/321307

**Comment by TianZhen000** [comment]
厉害了

**Comment by shristy123** [comment]
<build>
      <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.eclipse.m2e</groupId>
                <artifactId>lifecycle-mapping</artifactId>
                <version>1.0.0</version>
                <configuration>
                    <lifecycleMappingMetadata>
                        <pluginExecutions>
                            <pluginExecution>
                                    <groupId>org.codehaus.mojo</groupId>
                                    <artifactId>aspectj-maven-plugin</artifactId>
                                    <versionRange>[1.0,)</versionRange> 
                                    <goals>
                                      <goal>compile</goal>
                                      <goal>test-compile</goal>
                                    </goals>
                            </pluginExecution>
                        </pluginExecutions>
                    </lifecycleMappingMetadata>
                </configuration>
            </plugin>
        </plugins>
    </pluginManagement>
</build>

**Comment by rstoyanchev** [comment]
Resolved via a30e404e00c17f8405bd3d81a6154c4432434456.

**Comment by monadgon** [comment]
![image](https://user-images.githubusercontent.com/511164/61696375-2f1ec980-ad70-11e9-8cc2-babdd4fc30a5.png)
