### ISSUE TITLE
Project has been tested on tomcat -8.5.24

### ISSUE THREAD

**Issue by alanmehio** [spring-projects/spring-mvc-showcase#66]
Hi,
There were some issue around ClassNotFoundException . So I have fixed the dependency which make it working now. 

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.9.3</version> 
		</dependency>

 
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>2.0.1.Final</version> 			
		</dependency>
		
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>6.0.7.Final</version> 
		</dependency>

It would be great if somebody upgrade the maven pom file. 

Regards,
Alan Meiho

**Comment by rstoyanchev** [comment]
Resolved via a30e404e00c17f8405bd3d81a6154c4432434456.
